-- CreateTable
CREATE TABLE "Author" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Product" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "title" TEXT NOT NULL,
    "isFiction" BOOLEAN NOT NULL,
    "datePublish" DATETIME NOT NULL,
    "authorID" INTEGER NOT NULL,
    CONSTRAINT "Product_authorID_fkey" FOREIGN KEY ("authorID") REFERENCES "Author" ("ID") ON DELETE CASCADE ON UPDATE CASCADE
);
